# Generated by Django 4.0.4 on 2022-05-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_alter_course_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="demo_time",
            field=models.TimeField(null=True),
        ),
    ]
