# Generated by Django 4.0.4 on 2022-05-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_address_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="users",
        ),
    ]
