# Generated by Django 4.0.4 on 2022-05-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_remove_address_users"),
        ("user_accounts", "0004_remove_kanvasuser_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanvasuser",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="address.address",
            ),
        ),
    ]
